import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Failure: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Failed to Tweet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Failure</h1>
      <p>Something went wrong tweeting your betslip receipt to Twitter. Please try again!</p>
      <button onClick={() => window.close()}></button>
    </div>
  )
}

export default Failure
