import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect } from 'react'
import styles from '../styles/Home.module.css'

const Success: NextPage = () => {

  useEffect(() => {
    window.open('','_self')?.close();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <h1>You are a WINNER!!!</h1>
    </div>
  )
}

export default Success
